/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicDashboardRouteImport } from './routes/_public/dashboard'
import { Route as PublicAboutRouteImport } from './routes/_public/about'
import { Route as ProtectedReservationRouteImport } from './routes/_protected/reservation'

const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/_public/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicDashboardRoute = PublicDashboardRouteImport.update({
  id: '/_public/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/_public/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedReservationRoute = ProtectedReservationRouteImport.update({
  id: '/_protected/reservation',
  path: '/reservation',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/reservation': typeof ProtectedReservationRoute
  '/about': typeof PublicAboutRoute
  '/dashboard': typeof PublicDashboardRoute
  '/': typeof PublicIndexRoute
}
export interface FileRoutesByTo {
  '/reservation': typeof ProtectedReservationRoute
  '/about': typeof PublicAboutRoute
  '/dashboard': typeof PublicDashboardRoute
  '/': typeof PublicIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected/reservation': typeof ProtectedReservationRoute
  '/_public/about': typeof PublicAboutRoute
  '/_public/dashboard': typeof PublicDashboardRoute
  '/_public/': typeof PublicIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/reservation' | '/about' | '/dashboard' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/reservation' | '/about' | '/dashboard' | '/'
  id:
    | '__root__'
    | '/_protected/reservation'
    | '/_public/about'
    | '/_public/dashboard'
    | '/_public/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedReservationRoute: typeof ProtectedReservationRoute
  PublicAboutRoute: typeof PublicAboutRoute
  PublicDashboardRoute: typeof PublicDashboardRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/dashboard': {
      id: '/_public/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof PublicDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/reservation': {
      id: '/_protected/reservation'
      path: '/reservation'
      fullPath: '/reservation'
      preLoaderRoute: typeof ProtectedReservationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  ProtectedReservationRoute: ProtectedReservationRoute,
  PublicAboutRoute: PublicAboutRoute,
  PublicDashboardRoute: PublicDashboardRoute,
  PublicIndexRoute: PublicIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
